# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Jekyll Theme
description: Just another Jekyll theme design and code by zhanxin.info.
keywords: Jekyll Theme
url: http://wayne-china.github.io
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
# - text: 联系我
#  url: /contact.html
#  - text: 友情链接
#   url: /links.html

#Author config
author:
    name: Rollingwayne
    email: rollingwayne@gmail.com
    imageLink: http://tp2.sinaimg.cn/1832671293/180/40020872447/1
    simpleIntro: 我是「Rollingwayne」
      <p>走在 Python 程序员向产品经理的转型之路上</p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/2505989942
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/wayne-china
  - class: icon-twitter
    url: http://twitter.com/xxyyfuture
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: 掌心
      url: http://wayne-china.github.io
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://wayne-china.github.io
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: true
  id: UA-40169250-1

#comment config
disqus:
  config: true
  id: piznblog

duoshuo:
  config: false
  id: zhanxin
